### ISSUE TITLE
DecimalTypeDecider does not specify which source column caused error

### ISSUE THREAD

**Issue by shorban-uod** [HicServices/RDMP#196] opened 2021-01-13 16:12 UTC
**Describe the bug**
When using a RemoteTableAttacher, the DecimalTypeDecider failed due to the value '.' in a certain column, however RDMP does not specify which column the value '.' originates from.

**To Reproduce**
1. Set up a data load to a target table containing a single column of the float data type
2. Create a DatabaseAttacher which uses the code "select '1';"
3. Run the data load

**Expected behavior**
Either:
1) DecimalTypeDecider chooses that '.' is an invalid decimal and sets the column to NULL
2) (Preferred) Add the source column to the error message so that the user can investigate and decide how to fix the problem in the RemoteTableAttacher code

**Screenshots**
![image](https://user-images.githubusercontent.com/67638363/104478020-b477e880-55b9-11eb-8c85-4833cc6fe242.png)
![image](https://user-images.githubusercontent.com/67638363/104478074-bf327d80-55b9-11eb-972d-7382af71c364.png)

**RDMP Version**
v4.2.0

**Error with Stack Trace**
Stack trace for screenshot 1:
```
Could not parse string value '.' with Decider Type:DecimalTypeDecider
   at TypeGuesser.Deciders.DecideTypesForStrings`1.Parse(String value)
   at FAnsi.Discovery.BulkCopy.ConvertStringTypesToHardTypes(DataTable dt)
   at FAnsi.Discovery.BulkCopy.Upload(DataTable dt)
   at Rdmp.Core.DataLoad.Engine.Pipeline.Destinations.SqlBulkInsertDestination.SubmitChunk(DataTable chunk, IDataLoadEventListener job) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataLoad\Engine\Pipeline\Destinations\SqlBulkInsertDestination.cs:line 67
   at Rdmp.Core.DataLoad.Engine.Pipeline.Destinations.SqlBulkInsertDestination.ProcessPipelineData(DataTable toProcess, IDataLoadEventListener listener, GracefulCancellationToken cancellationToken) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataLoad\Engine\Pipeline\Destinations\SqlBulkInsertDestination.cs:line 173
   at Rdmp.Core.DataFlowPipeline.DataFlowPipelineEngine`1.ExecuteSinglePass(GracefulCancellationToken cancellationToken) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataFlowPipeline\DataFlowPipelineEngine.cs:line 220
   at Rdmp.Core.DataFlowPipeline.DataFlowPipelineEngine`1.ExecutePipeline(GracefulCancellationToken cancellationToken) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataFlowPipeline\DataFlowPipelineEngine.cs:line 110
'.' (System.String) is not convertible to 'System.Decimal'.
   at TB.ComponentModel.TypeConverter.Convert(Object value, Type destinationType, CultureInfo culture)
   at TB.ComponentModel.TypeConverter.ConvertTo[T](Object value, CultureInfo culture)
   at TypeGuesser.Deciders.DecideTypesForStrings`1.ParseImpl(String value)
   at TypeGuesser.Deciders.DecideTypesForStrings`1.Parse(String value)
```

Stack trace for screenshot 2:
```
Data Flow Pipeline Crashed
   at Rdmp.Core.DataFlowPipeline.DataFlowPipelineEngine`1.ExecutePipeline(GracefulCancellationToken cancellationToken) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataFlowPipeline\DataFlowPipelineEngine.cs:line 182
   at Rdmp.Core.DataLoad.Modules.Attachers.RemoteTableAttacher.Attach(IDataLoadJob job, GracefulCancellationToken cancellationToken) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataLoad\Modules\Attachers\RemoteTableAttacher.cs:line 385
   at Rdmp.Core.DataLoad.Engine.LoadExecution.Components.Runtime.AttacherRuntimeTask.Run(IDataLoadJob job, GracefulCancellationToken cancellationToken) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataLoad\Engine\LoadExecution\Components\Runtime\AttacherRuntimeTask.cs:line 49
Could not parse string value '.' with Decider Type:DecimalTypeDecider
   at TypeGuesser.Deciders.DecideTypesForStrings`1.Parse(String value)
   at FAnsi.Discovery.BulkCopy.ConvertStringTypesToHardTypes(DataTable dt)
   at FAnsi.Discovery.BulkCopy.Upload(DataTable dt)
   at Rdmp.Core.DataLoad.Engine.Pipeline.Destinations.SqlBulkInsertDestination.SubmitChunk(DataTable chunk, IDataLoadEventListener job) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataLoad\Engine\Pipeline\Destinations\SqlBulkInsertDestination.cs:line 67
   at Rdmp.Core.DataLoad.Engine.Pipeline.Destinations.SqlBulkInsertDestination.ProcessPipelineData(DataTable toProcess, IDataLoadEventListener listener, GracefulCancellationToken cancellationToken) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataLoad\Engine\Pipeline\Destinations\SqlBulkInsertDestination.cs:line 173
   at Rdmp.Core.DataFlowPipeline.DataFlowPipelineEngine`1.ExecuteSinglePass(GracefulCancellationToken cancellationToken) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataFlowPipeline\DataFlowPipelineEngine.cs:line 220
   at Rdmp.Core.DataFlowPipeline.DataFlowPipelineEngine`1.ExecutePipeline(GracefulCancellationToken cancellationToken) in D:\Jenkins\workspace\RDMP\HIC.RDMP.GitHub.Release\Rdmp.Core\DataFlowPipeline\DataFlowPipelineEngine.cs:line 110
'.' (System.String) is not convertible to 'System.Decimal'.
   at TB.ComponentModel.TypeConverter.Convert(Object value, Type destinationType, CultureInfo culture)
   at TB.ComponentModel.TypeConverter.ConvertTo[T](Object value, CultureInfo culture)
   at TypeGuesser.Deciders.DecideTypesForStrings`1.ParseImpl(String value)
   at TypeGuesser.Deciders.DecideTypesForStrings`1.Parse(String value)
```

**Database Engine**
Sql Server

**Additional context**

**Comment by tznind** [comment] 2021-01-18 07:33
This is a duplicate of #197

**Closed by tznind** 2021-01-18 07:33 UTC
